const creditCards = [
  {
    id: 1,
    name: "Premium Travel Rewards",
    issuer: "Capital One",
    image: "/placeholder.svg?height=200&width=300",
    annualFee: "$95",
    rewardsRate: "2x-5x",
    welcomeBonus: "75,000 points",
    apr: "18.99% - 26.99%",
    creditScore: "Excellent",
    features: [
      "5x points on travel",
      "3x points on dining",
      "2x points on everything else",
      "No foreign transaction fees",
      "Travel insurance",
    ],
    rating: 4.8,
    bestFor: "Travel",
  },
  {
    id: 2,
    name: "Ultimate Cash Back",
    issuer: "Chase",
    image: "/placeholder.svg?height=200&width=300",
    annualFee: "$0",
    rewardsRate: "1.5%-5%",
    welcomeBonus: "$200",
    apr: "17.99% - 25.99%",
    creditScore: "Good to Excellent",
    features: [
      "5% cash back on rotating categories",
      "3% on dining and drugstores",
      "1.5% on everything else",
      "No annual fee",
      "0% intro APR for 15 months",
    ],
    rating: 4.7,
    bestFor: "Cash Back",
  },
  {
    id: 3,
    name: "Balance Transfer Plus",
    issuer: "Citi",
    image: "/placeholder.svg?height=200&width=300",
    annualFee: "$0",
    rewardsRate: "1%-2%",
    welcomeBonus: "None",
    apr: "0% intro for 21 months, then 16.99% - 26.99%",
    creditScore: "Good",
    features: [
      "0% intro APR on balance transfers for 21 months",
      "0% intro APR on purchases for 12 months",
      "No late fees",
      "No penalty rate",
      "2% cash back on groceries and gas",
    ],
    rating: 4.5,
    bestFor: "Balance Transfer",
  },
  {
    id: 4,
    name: "Student Rewards Builder",
    issuer: "Discover",
    image: "/placeholder.svg?height=200&width=300",
    annualFee: "$0",
    rewardsRate: "1%-5%",
    welcomeBonus: "Cashback Match",
    apr: "15.99% - 24.99%",
    creditScore: "Fair to Good",
    features: [
      "5% cash back on rotating categories",
      "1% cash back on all other purchases",
      "No annual fee",
      "No foreign transaction fees",
      "Free FICO score",
    ],
    rating: 4.6,
    bestFor: "Students",
  },
  {
    id: 5,
    name: "Business Rewards Plus",
    issuer: "American Express",
    image: "/placeholder.svg?height=200&width=300",
    annualFee: "$295",
    rewardsRate: "1.5x-4x",
    welcomeBonus: "100,000 points",
    apr: "17.99% - 25.99%",
    creditScore: "Good to Excellent",
    features: [
      "4x points on business categories",
      "2x points on travel",
      "1.5x points on everything else",
      "Annual statement credits",
      "Travel and purchase protections",
    ],
  }]